### ISSUE TITLE
Make new/3 public

### ISSUE THREAD

**Issue by kipcole9** [wojtekmach/calendar_interval#11]
`Calendar.Interval.new/3` is currently a private function however it has valid public use cases where creating an interval between two arbitrary naive_date_times with a given precision is a requirement.  Consider making it public?

**Comment by wojtekmach** [comment]
I'm worried that introducing +1 arity version my come back to bite us later, for whatever reason we'd add `opts \\ []` at the end and then we'd have "conflicting" arities. Maybe it's overly cautious though.

WDYT about:

```elixir
CalendarInterval.new({~N[2020-01-01 09:00:00], ~N[2020-12-31 23:59:59]}, :minute)
```

**Comment by kipcole9** [comment]
Yes, I think the tuple form is perfectly fine. Not a million examples in Elixir libs but I have used that pattern for the same reason in a few cases.

I still think this library does not get nearly enough visibility in the community - simply because its not well understood and you (like me) aren’t focused on community marketing :-)

I’m about to get back into blogging mode so maybe I’ll write something about it this weekend.

**Comment by wojtekmach** [comment]
Since we support them in new/2, I think we should also support passing dates and so we may as well allow `%Date.Range{}`, these should be equivalent:

```elixir
CalendarInterval.new({~D[2020-01-01], ~D[2020-12-31]}, :minute)
CalendarInterval.new(Date.range(~D[2020-01-01], ~D[2020-12-31]), :minute)
```

which begs the question, howe come we don't yet have NaiveDateTime.Range (and DateTime.Range) in the stdlib? :) (Well, if we had, there would be less reason for this library to exist!) That's a totally separate discussion, which I'm happy to have here and/or elsewhere. To me, the biggest advantages of this library are:

1. a notion of precision
2. the compact iso8601 representation
3. allen interval algebra
4. low-level operations (nest, enclosing, prev, next) that can be composed

regarding low-level operations, maybe it's just it's been a long time since I needed to do complicated date operations, but that feature somewhat lost it's appeal to me.  In any case, if we were to propose this to stdlib, would we include all 4 things, or just a subset? what's the minimal set of features that seems useful?

**Comment by kipcole9** [comment]
I think your discussion above explain why its not really ready for a `stdlib` discussion. And I think there are precious few of us interested in this topic :-). Although I do note that I have seen a few discussion on "how to I enumerate a date or date time range".

And additional consideration here is the nature of the interval. As defined by `CalendarInterval` the interval is `closed` (both left- and right-closed).  [Timex.Interval](https://hexdocs.pm/timex/3.0.5/Timex.Interval.html#new/1) is left-closed and right-option which, if I understand correctly, is the more common form.  Adopting this form would obviate the work you do to add `23:59:59.999999` on dates coerced into native date times.

I agree with all of the value propositions for `CalendarInterval` you state above, thats why I keep coming back. I'd like to thing it could, some day, form the basis of an additional to `stdlib`.

To do that I think the following questions need to be resolved:

1. Dates only (like `Date.Range` - which was added because it is the simple case) or allow `NaiveDateTime` and `DateTime` and `Time` as well?  Dates would have to be in the same timezone I believe (conversion to the same timezone is a programmer responsibility).

2. Would arguments have to be the same structures or would support for extending a structure be provided?. ie if you pass a `date` and a `naivedatetime`, would you extend the date to become a `naivedatetime`?

2. Open or closed ranges, or definable like `Timex` and `Joda time`.

3. API includes the lower level operations?

Overall, my opinion would be:

1. Allow all date/time structures
2. Extend dates to datetime if the other argument is a date time
3. Default to left-closed, right-open (breaking change I know)

**Comment by wojtekmach** [comment]
Thanks Kip!

> Overall, my opinion would be:

Do you mean these in the context of calendar_interval or stdlib or both?

> 1. Allow all date/time structures

Agreed.

> 2. Extend dates to datetime if the other argument is a date time

I think I'd start with ensuring both arguments are of the same type so I'd hold off on that. I think I'd go as far as ensuring the *Time structs have the same microseconds precision. I think it's reasonable enough to expect the caller to normalise the data before passing to us, though I must say it is *extremely* convenient to do stuff like `Date.add(naive_datetime, 1)`, so I'd be happy to revisit this in the future obviously.

> 3. Default to left-closed, right-open (breaking change I know)

Yeah, it seems to be way more common. Funny that you mention, we just run into this the other day with a client that PG is normalising to right-open:

```
wojtek=# select '[2020-01-01,2020-01-02)'::daterange;
        daterange
-------------------------
 [2020-01-01,2020-01-02)
(1 row)

wojtek=# select '[2020-01-01,2020-01-02]'::daterange;
        daterange
-------------------------
 [2020-01-01,2020-01-03)
```

I believe I even started with being right-open and then switched to be right-closed to mirror stdlib's `Date.Range` semantics. Though I haven't heard of any discussions around it, I believe it would totally be possible to add left & right inclusivity to `%Date.Range{}` in a backwards compatible way (we'd default to inclusive), so that's encouraging.

Semantically, I think it also make sense to be right-open for an unbounded range on the right side, there are no current plans to support unbounded ranges but eventually I think we should have them too since ISO 8601 has them.

---

I think the next steps for me would be in no particular order:

- ~adding new/3 per this issue~ extending new/2 per this issue
- point 1. from discussion above
- probably point 3. from discussion above
- https://github.com/wojtekmach/calendar_interval/issues/7

**Comment by kipcole9** [comment]
I like how this discussion is progressing ideas around a challenging but valuable topic.

#### Extending parameters

Extending parameters. You are right, its a programmer responsibility.  Converting a `naivedatetime` to `datetime` is very straight forward.  Converting `date` to `naivedatetime` or `datetime` seems to like a simple API though and this is always a pain.  We have `NaiveDateTime.from_erl/2` and `from_iso8601/1` but not `from_date`. Do you sense whether a proposal to add that would be considered?  It's something I can work on.

#### Doing the work

I'm more than happy to pitch in and do some work here so let me know which items, if any, you want me to work on.

#### Enhancing Date.Range

Once the work here is complete, I'm also fine to work on a PR for `Date.Range` to add optional closure configuration to it.  I think proving out the closures here would be a good first step.

#### Unbounded ranges

And now I'm curious so back to the spec I go ... :-)

**Comment by kipcole9** [comment]
It would be great if, at the end of this journey, `CalendarInterval` was something that could be considered to become `Calendar.Interval` :-)

**Comment by wojtekmach** [comment]
> We have NaiveDateTime.from_erl/2 and from_iso8601/1 but not from_date. Do you sense whether a proposal to add that would be considered?

Good question. Today we can do: `NaiveDateTime.new(date, ~T[00:00:00])` (there's a new!/2 variant on master too) which is more explicit, notably you set your microsecond precision. So I'd say it's unlikely from_date/1 would be accepted but it very well might be.

> let me know which items, if any, you want me to work on.

feel free to pick any items from this list, thank you!

> I'm also fine to work on a PR for Date.Range to add optional closure configuration to it. I think proving out the closures here would be a good first step.

Yeah, we should first solve it here and then include it I the potential proposal to stdlib.

I keep going back'n'forth about closure information. If right-open is the way to go but we want to allow different representations as input, we should normalise to that internally. If we don't normalise internally I think internal calculations would be much more complicated (e.g. the Enumerable implementation, interval algebra, etc) because we'd have to constantly check if we're open/closed. As far as the input goes, I'm mostly interested in supporting iso 8601 and my understanding is it is always right-closed, e.g.: `2020/2021` is right-closed. On the other hand, if being able to represent right-open ranges is important, and I can't help but wonder that it really is, it's fine to make the internal computations more complicated because we only have to get them right once and then the consumers of the library don't have to worry about it.

> It would be great if, at the end of this journey, CalendarInterval was something that could be considered to become Calendar.Interval :-)

That was the plan all along!

**Comment by kipcole9** [comment]
I'll start with updating `new/2` for the 2-tuple form and the `Date.Range` form. Tackle the easy things first :-)

For closures. I think its like this for me:

1. For `dates` (having no time), being closed makes more logical sense. `2020-2021` would be considered closed for most (all?) readers. Enumerating that range would expect to include the final value.

2. For `datetimes`, I feel like being right open is the more normal expectation:
`2020-01-01 00:00:00` / `2021-01-01 00:00:00` would, if I think of enumeration, probably **not** expect to include the final value.

Thats why I keep going backwards and forwards on this too. So for now, I'll just avoid the issue until someone smarter than me can resolve the two cases into a harmonious unified theory.
